language: java
jdk:
- openjdk8
addons:
  ssh_known_hosts:
  - 116.196.86.186
install:
 - ./mvnw clean
script: ./mvnw clean package -Dmaven.test.skip=true -DskipTests
after_success:
- ls -al
- pwd
- scp -P 3222 -o stricthostkeychecking=no -r ./start/target/b_proxy.jar web@116.196.86.186:/home/web/b_proxy/

- scp -P 3222 -o stricthostkeychecking=no -r ./restart.sh web@116.196.86.186:/home/web/b_proxy/
- ssh web@116.196.86.186 -p 3222 -o stricthostkeychecking=no "sh /home/web/b_proxy/restart.sh
  aliyun 8092"
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600  ~/.ssh/id_rsa 
- echo -e "Host 116.196.86.186\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod a+x ./mvnw

